[package]
name = "chirp"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
hound = "3.5.1"
jack = "0.13.2"
liquid-dsp-sys = { path = "../liquid_dsp_sys", version = "0.1.0" }
thiserror = "2.0.12"
once_cell = "1.21"
bitstream-io = "4.2"

[dev-dependencies]
rstest = "0.25"
